name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

      - name: Build extensions
        run: bash scripts/build.sh

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65  # v2
        with:
          files: |
            dist/chrome.zip
            dist/firefox.zip
            dist/firefox.xpi
          generate_release_notes: true
